import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";
import TopLeftImg from "@/components/TopLeftImg";
import AnimateAppScreen from "@/components/AnimateAppScreen";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.variable}>
        <AnimateAppScreen>
          <div
            className={`page bg-site text-white bg-cover bg-no-repeat font-sora relative`}
          >
            <TopLeftImg />
            <Navbar />
            <Header />
            {children}
          </div>
        </AnimateAppScreen>
      </body>
    </html>
  );
}
